name = "SysInfo"
uuid = "90a7ee08-a23f-48b9-9006-0e0e2a9e4608"
authors = ["Carsten Bauer <crstnbr@gmail.com> and contributors"]
version = "0.1"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Hwloc = "0e44f5e4-bd66-52a0-8798-143a42290a1d"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
DelimitedFiles = "1"
Hwloc = "3.1"
PrecompileTools = "1.2"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
