name = "SysInfo"
uuid = "90a7ee08-a23f-48b9-9006-0e0e2a9e4608"
authors = ["Carsten Bauer <crstnbr@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Hwloc = "0e44f5e4-bd66-52a0-8798-143a42290a1d"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"

[compat]
Hwloc = "3.0"
PrettyTables = "2.3"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
